{% set name = "gyptis" %}
{% set version = "1.0.2" %}


package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://gitlab.com/{{ name }}/{{ name }}/-/archive/v{{ version }}/{{ name }}-v{{ version }}.tar.gz
  sha256: 5d57196a6e3519a24b334cb92a7c0042d52ba3b0d31e7b29dfdf5e88ed7cdeb4


build:
  number: 1
  script: "{{ PYTHON }} -m pip install . -vv --no-deps"
  skip: true  # [win]
  {% set mpi_prefix = "mpi_" + mpi %}
requirements:
  build:
    - {{ compiler('cxx') }}
    - {{ stdlib("c") }}
    - {{ cdt('libselinux') }}        # [linux]
    - {{ cdt('libxcb') }}            # [linux]
    - {{ cdt('libxau') }}            # [linux]
    - {{ cdt('libxdamage') }}        # [linux]
    - {{ cdt('libxxf86vm') }}        # [linux]
    - {{ cdt('mesa-libgl-devel') }}  # [linux]
    - {{ cdt('mesa-dri-drivers') }}  # [linux]
  host:
    - python
    - pip
    - fenics
    - numpy
    - {{ mpi }}
    - xorg-libxfixes     # [linux]
    - xorg-libxext       # [linux]
    - xorg-libxrender    # [linux]
    - xorg-libx11        # [linux]
    - xorg-libxmu        # [linux]
  run:
    - python
    - fenics
    - numpy
    - dolfin-adjoint
    - gmsh 
    - python-gmsh
    - meshio
    - scipy
    - matplotlib-base
    - nlopt
    - psutil
    - ipython
    - joblib
    - loguru
    - {{ mpi }}
    - h5py * {{ mpi_prefix }}_*

test:
  imports:
    - {{ name }}
  source_files:
    - tests/simple_test.py
  commands:
    - export MPLBACKEND=agg && unset GYPTIS_ADJOINT && pytest -svv ./tests/simple_test.py
  requires:
    - pytest

about:
  home: https://gitlab.com/{{ name }}/{{ name }}
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: 'Computational Photonics in Python'

  description: |
    Gyptis is a package to solve problems relevant in Electromagnetism and Photonics. 
    It is built on top of Gmsh <https://gmsh.info> for defining and meshing geometries and 
    FEniCS <https://fenicsproject.org> to solve Maxwell's equations with the Finite Element Method.
  doc_url: https://{{ name }}.gitlab.io
  dev_url: https://gitlab.com/{{ name }}/{{ name }}

extra:
  recipe-maintainers:
    - benvial
